# Generated by Django 5.1.2 on 2025-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avance',
            field=models.TextField(default='Sin avance'),
        ),
    ]
