# Generated by Django 5.1.2 on 2025-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_usuario_avance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avance',
        ),
        migrations.AddField(
            model_name='tarea',
            name='avance',
            field=models.TextField(default='Sin avance'),
        ),
    ]
